version: '3.3'

services:
  postgres:
    image: "postgres:15"
    ports:
      - "5455:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoUser"
      MONGO_INITDB_ROOT_PASSWORD: "mongoPassword"
      MONGO_INITDB_DATABASE: "mongoDb"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
  memcached:
    image: "memcached:latest"
    ports:
      - "11211:11211"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    deploy:
      resources:
        limits:
          memory: 2048m
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/data/elasticsearch
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch                                   # kibana will start when elasticsearch has started

volumes:
  pg_data:
  mongodb-data:
  elasticsearch-data:
