version: '3.8'

x-logging:
  - &logging
    logging:
      options:
        max-size: '20m'
        max-file: '5'
      driver: json-file

services:
  postgres:
    image: "postgres:15"
    ports:
      - "5455:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoUser"
      MONGO_INITDB_ROOT_PASSWORD: "mongoPassword"
      MONGO_INITDB_DATABASE: "mongoDb"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  pg_data:
  mongodb-data:
